language:
    - cpp

compiler:
    - clang
    - gcc

env:
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release"
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Release"
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Debug"
    - BUILD_EXAMPLES="ON" BUILD_TESTS="ON" BUILD_SHARED_LIBS="OFF" CMAKE_BUILD_TYPE="Debug"

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes # libstdc++-4.8
    - if [ "${CXX}" == "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi
    - sudo apt-get update

install:
    - if [ "${CXX}" == "clang++" ]; then sudo apt-get -qq install clang-3.3; fi
    - sudo apt-get install g++-4.8;
    - sudo update-alternatives --install /usr/bin/gcc-4.8 gcc /usr/bin/gcc 50
    - sudo update-alternatives --install /usr/bin/g++-4.8 g++ /usr/bin/g++ 50
    - wget http://jaist.dl.sourceforge.net/boost/boost_1_54_0.tar.bz2
    - tar -xf boost_1_54_0.tar.bz2
    - ( cd boost_1_54_0  && ./bootstrap.sh --prefix=/usr && sudo ./b2 -j2 release architecture=x86 address-model=64 --with-system --with-thread --with-test --with-log install ) > /dev/null
    - sudo rm -rf boost_1_54_0

before_script:
    # update compilers
    - if [ "${CXX}" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - if [ "${CXX}" == "clang++" ]; then export CXX="clang++-3.3" CC="clang-3.3"; fi

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DBUILD_TESTS=${BUILD_TESTS} -DBUILD_EXAMPLES=${BUILD_EXAMPLES} ..
    - make VERBOSE=1
    - make test
